FROM arm32v7/python:3.7.2-slim

LABEL maintainer="dirtycajunrice"

WORKDIR /app

COPY /qemu-arm-static /usr/bin/qemu-arm-static

COPY /ws_counter.py /requirements.txt /README.md /app/

RUN python3 -m pip install -r /app/requirements.txt

ENV INFLUXDB_DBNAME plex
ENV INFLUXDB_URL localhost
ENV INFLUXDB_PORT 8086
ENV POLL_INCREMENT 30
ENV PLEX_URL localhost:32400
ENV PLEX_TOKEN xxxxxxxxxxxxxxxx

# Run app.py when the container launches
CMD ["python", "ws_counter.py"]